# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'JS 30'
tagline:          'A Jekyll theme'
description:      'A website to store my solutions for JavaScript 30 challenge conducted by Wes Bos'
url:              'https://aigle-levant.github.io/js-30/'
baseurl: '/'

author:
  name:           'Aigle'
  url:            https://github.com/aigle-levant

plugins:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aigle-levant/js-30
