# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            JavaScript 30
tagline:          'A Jekyll theme'
description:      'A website to store my solutions'
url:              'https://aigle-levant.github.io/js-30/'

author:
  name:           'Aigle'
  url:            https://twitter.com/mdo

gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
